# Generated by Django 4.1.3 on 2022-11-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FondDocs',
            new_name='FondDocument',
        ),
    ]
