# Generated by Django 4.1.3 on 2022-11-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_nkoevent_alter_address_options_delete_event_and_more'),
        ('root', '0002_rename_fonddocs_fonddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutNKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'About NKO',
                'verbose_name_plural': 'About NKO',
            },
        ),
        migrations.CreateModel(
            name='MediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_url', models.URLField(blank=True, verbose_name='vk url')),
                ('inst_url', models.URLField(blank=True, verbose_name='instagram url')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='phone number')),
                ('owner', models.CharField(blank=True, max_length=128, verbose_name='NKO Owner')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.address')),
            ],
            options={
                'verbose_name': 'Media links',
                'verbose_name_plural': 'Media links',
            },
        ),
    ]
