# Generated by Django 4.1.3 on 2022-11-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_question_answer_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='fonddocument',
            options={'verbose_name': 'fond document', 'verbose_name_plural': 'fond documents'},
        ),
    ]
