# Generated by Django 4.1.3 on 2022-11-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonddocument',
            name='files',
        ),
        migrations.AddField(
            model_name='fonddocument',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fond_docs', to='root.file'),
            preserve_default=False,
        ),
    ]
