# Generated by Django 4.1.6 on 2023-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_contacts_telegram_alter_contacts_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='фото для галлереи')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutTheFund',
        ),
    ]
