# Generated by Django 4.1.6 on 2023-02-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_gallery_delete_aboutthefund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'галлерея', 'verbose_name_plural': 'галлерея'},
        ),
    ]
