# Generated by Django 4.1.3 on 2022-11-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created_at',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
