# Generated by Django 4.1.3 on 2022-11-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_nkoevent_is_finished'),
        ('root', '0006_alter_file_options_alter_fonddocument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_url', models.URLField(blank=True, verbose_name='vk url')),
                ('inst_url', models.URLField(blank=True, verbose_name='instagram url')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='phone number')),
                ('owner', models.CharField(blank=True, max_length=128, verbose_name='The fund owner')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.address')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.RenameModel(
            old_name='AboutNKO',
            new_name='AboutTheFund',
        ),
        migrations.AlterModelOptions(
            name='aboutthefund',
            options={'verbose_name': 'About the fund', 'verbose_name_plural': 'About the fund'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='question',
        ),
        migrations.DeleteModel(
            name='MediaLinks',
        ),
    ]
