# Generated by Django 4.1.3 on 2022-11-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_fundevent_addresses_alter_fundevent_files_and_more'),
        ('root', '0010_delete_fonddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='root.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.address', verbose_name='address'),
        ),
    ]
