# Generated by Django 4.1.3 on 2022-12-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_answer_question_alter_contacts_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
