# Generated by Django 4.1.3 on 2022-12-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_fundevent_is_online_alter_fundevent_addresses_and_more'),
        ('root', '0013_remove_contacts_inst_url_contacts_ok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='phone number'),
        ),
    ]
