# Generated by Django 4.1.3 on 2022-11-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='description')),
                ('start_timestamp', models.DateTimeField(verbose_name='start')),
                ('end_timestamp', models.DateTimeField(verbose_name='end')),
                ('is_finished', models.BooleanField(db_index=True, help_text='Is this project has finished?')),
                ('files', models.ManyToManyField(related_name='projects', to='root.file')),
                ('partners', models.ManyToManyField(related_name='projects', to='projects.partner')),
            ],
        ),
    ]
