# Generated by Django 4.1.6 on 2023-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_url',
            field=models.URLField(default='', verbose_name='Ссылка на партнера'),
            preserve_default=False,
        ),
    ]
