# Generated by Django 4.1.3 on 2022-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',), 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('start_timestamp',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='end_timestamp',
            field=models.DateTimeField(verbose_name='end timestamp'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_timestamp',
            field=models.DateTimeField(verbose_name='start timestamp'),
        ),
    ]
