# Generated by Django 4.1.6 on 2023-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_partner_partner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='', upload_to='', verbose_name='фото проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_url',
            field=models.URLField(verbose_name='Ссылка на партнера:'),
        ),
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
    ]
