# Generated by Django 4.1.3 on 2022-12-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_delete_answer_delete_question'),
        ('projects', '0005_partner_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='root.file', verbose_name='files'),
            preserve_default=False,
        ),
    ]
