# Generated by Django 4.1.6 on 2023-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_partners_alter_partner_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners', verbose_name='logo'),
        ),
    ]
