# Generated by Django 4.1.6 on 2023-02-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
    ]
