# Generated by Django 4.1.6 on 2023-02-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='project type')),
            ],
            options={
                'verbose_name': 'project type',
                'verbose_name_plural': 'projects types',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_finished',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='projects.projecttype'),
            preserve_default=False,
        ),
    ]
