# Generated by Django 4.1.6 on 2023-02-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projecttype_remove_project_is_finished_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ('name',), 'verbose_name': 'тип проекта', 'verbose_name_plural': 'типы проектов'},
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='тип проекта'),
        ),
    ]
