# Generated by Django 4.1.6 on 2023-02-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projecttype_options_alter_projecttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projecttype', verbose_name='тип проекта'),
        ),
    ]
