# Generated by Django 4.1.3 on 2022-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_answer_question_alter_contacts_address'),
        ('projects', '0002_alter_partner_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(related_name='projects', to='root.file', verbose_name='files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(db_index=True, help_text='Is this project has finished?', verbose_name='is finished'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(related_name='projects', to='projects.partner', verbose_name='partners'),
        ),
    ]
