# Generated by Django 4.1.3 on 2022-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_delete_answer_delete_question'),
        ('projects', '0004_alter_project_files_alter_project_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ManyToManyField(blank=True, related_name='partners', to='root.file', verbose_name='files'),
        ),
    ]
