# Generated by Django 4.1.3 on 2022-12-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_remove_contacts_inst_url_contacts_ok_url'),
        ('projects', '0006_remove_partner_logo_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='root.file', verbose_name='logo'),
        ),
    ]
