# Generated by Django 4.1.3 on 2022-11-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='activity type')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='activity name')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='activity description')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activities.activitytype')),
                ('files', models.ManyToManyField(related_name='activities', to='root.file')),
            ],
        ),
    ]
