# Generated by Django 4.1.3 on 2022-11-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('name',), 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ('name',), 'verbose_name': 'activity type', 'verbose_name_plural': 'activities types'},
        ),
    ]
