# Generated by Django 4.1.3 on 2022-11-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_delete_fonddocument'),
        ('activities', '0002_alter_activity_options_alter_activitytype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activities.activitytype', verbose_name='activity type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=models.ManyToManyField(related_name='activities', to='root.file', verbose_name='files'),
        ),
    ]
