# Generated by Django 4.1.6 on 2023-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_created_at_alter_news_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='files',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description',
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
