# Generated by Django 4.1.6 on 2023-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_files_remove_news_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
    ]
