# Generated by Django 4.1.6 on 2023-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='short description'),
        ),
    ]
