# Generated by Django 4.1.3 on 2022-11-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NKOEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='description')),
                ('start_timestamp', models.DateTimeField(verbose_name='start timestamp')),
                ('end_timestamp', models.DateTimeField(verbose_name='end timestamp')),
                ('is_finished', models.BooleanField(db_index=True, help_text='Is this event has finished?')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('start_timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('address',), 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='nkoevent',
            name='address',
            field=models.ManyToManyField(related_name='events', to='events.address'),
        ),
        migrations.AddField(
            model_name='nkoevent',
            name='files',
            field=models.ManyToManyField(related_name='events', to='root.file'),
        ),
    ]
