# Generated by Django 4.1.3 on 2022-11-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_nkoevent_is_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nkoevent',
            old_name='address',
            new_name='addresses',
        ),
    ]
