# Generated by Django 4.1.3 on 2022-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_delete_answer_delete_question'),
        ('events', '0006_alter_fundevent_addresses_alter_fundevent_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundevent',
            name='is_online',
            field=models.BooleanField(db_index=True, default=1, help_text='Is this event will conduct in online mode?', verbose_name='online mode?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundevent',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.address', verbose_name='addresses'),
        ),
        migrations.AlterField(
            model_name='fundevent',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='events', to='root.file', verbose_name='files'),
        ),
    ]
