# Generated by Django 4.1.6 on 2023-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_fundevent_is_online_alter_fundevent_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundevent',
            name='files',
        ),
        migrations.RemoveField(
            model_name='fundevent',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='fundevent',
            name='picture',
            field=models.ImageField(default=1, upload_to='', verbose_name='photo'),
            preserve_default=False,
        ),
    ]
