# Generated by Django 4.1.6 on 2023-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_fundevent_files_remove_fundevent_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundevent',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='короткое описание'),
        ),
    ]
