# Generated by Django 4.1.3 on 2022-11-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_contacts_rename_aboutnko_aboutthefund_and_more'),
        ('events', '0004_rename_address_nkoevent_addresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NKOEvent',
            new_name='FundEvent',
        ),
    ]
