# Generated by Django 4.1.3 on 2022-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_delete_fonddocument'),
        ('events', '0005_rename_nkoevent_fundevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundevent',
            name='addresses',
            field=models.ManyToManyField(related_name='events', to='events.address', verbose_name='addresses'),
        ),
        migrations.AlterField(
            model_name='fundevent',
            name='files',
            field=models.ManyToManyField(related_name='events', to='root.file', verbose_name='files'),
        ),
        migrations.AlterField(
            model_name='fundevent',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this event has finished?', verbose_name='is finished'),
        ),
    ]
